version: '3'

services:
  api:
    build: .
    command: >
      /bin/sh -c "
      python manage.py migrate --noinput
      && gunicorn --bind 0.0.0.0:8000 core.wsgi:application
      && celery -A core worker -l info
      && celery -A core beat -l info"
    volumes:
      - .:/code
    expose:
      - "8000"
    env_file:
      - .env
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
  nginx3:
    build: ./nginx
    restart: unless-stopped
    ports:
      - 8005:8005
    depends_on:
      - api
    links:
      - api