# Generated by Django 3.0.6 on 2020-05-27 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_auto_20200506_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisualCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VisualRecovered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(null=True)),
                ('recovered', models.IntegerField(null=True)),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cases.VisualCountry')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='VisualDeaths',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(null=True)),
                ('deaths', models.IntegerField(null=True)),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cases.VisualCountry')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='VisualCases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(null=True)),
                ('cases', models.IntegerField(null=True)),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cases.VisualCountry')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
