# Generated by Django 3.0.6 on 2020-05-27 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_visualcases_visualcountry_visualdeaths_visualrecovered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualcases',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.VisualCountry'),
        ),
        migrations.AlterField(
            model_name='visualdeaths',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.VisualCountry'),
        ),
        migrations.AlterField(
            model_name='visualrecovered',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.VisualCountry'),
        ),
    ]
